site_name: OrcaSlicer WIKI
site_description: OrcaSlicer Docs and reference
repo_url: https://github.com/SoftFever/OrcaSlicer

theme:
  name: material
  logo: assets/images/orcaslicer-logo.png
  favicon: assets/images/orcaslicer-logo.ico
  language: en

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      TIP: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette: 
    - media: "(prefers-color-scheme)"
      primary: teal
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
  - navigation.tabs
  - search.suggest
  - navigation.footer
  - navigation.top
  - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  
  - Print Settings:
    - Quality Setting:
      - Layer Height: print-settings/quality/quality_settings_layer_height.md
      - Line Width: print-settings/quality/quality_settings_line_width.md
      - Precise Wall: print-settings/quality/precise-wall.md
      - Precise Z Height: print-settings/quality/precise-z-height.md
      - Seam: print-settings/quality/quality_settings_seam.md
    - Speed: print-settings/speed/extrusion-rate-smoothing.md
    - Multi Material: print-settings/multi-material/semm.md
  
  - Printer Settings:
    - Air Filtration/Exhaust Fan: printer-settings/air-filtration.md
    - Auxiliary Fan Handling: printer-settings/Auxiliary-fan.md
    - Chamber Temperature Control: printer-settings/Chamber-temperature.md
    - Adaptive Bed Mesh: printer-settings/adaptive-bed-mesh.md
    - Different Bed Types: printer-settings/bed-types.md
    - Pellet Printers: printer-settings/pellet-flow-coefficient.md

  - Printer Calibration: 
    - Calibration: calibration/calibration.md
    - Adaptive Pressure Advance: calibration/adaptive-pressure-advance.md
  
  - Developer Reference:
    - For Developers: developer-reference/dev-ref.md
    - Build Orca Slicer: developer-reference/How-to-build.md
    - Localization: developer-reference/Localization_guide.md
