name: Build macOS ARM64 (Scheduled)

on:
  push:
    branches:
     - main
     - release/*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - 'localization/**'
     - 'resources/**'
     - ".github/workflows/build_*.yml"
     - 'build_release_macos.sh'

  pull_request:
    branches:
     - main
     - release/*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - ".github/workflows/build_*.yml"
     - 'build_release_macos.sh'

  schedule:
      - cron: '35 7 * * *' # run once a day near midnight US Pacific time

  workflow_dispatch: # allows for manual dispatch
    inputs:
      build-deps-only:
        description: 'Only build dependencies (bypasses caching)'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  

jobs:
  build_macos:
    name: Build macOS ARM64
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: macos-14
      arch: arm64
      build-deps-only: ${{ inputs.build-deps-only || false }}
      force-build: ${{ github.event_name == 'schedule' }}
    secrets: inherit
